services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./app:/var/www:cached
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    links:
      - php-fpm
    restart: always
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www:cached
    restart: always
    user: "${APP_UID:-10001}:${APP_GID:-10001}"
    environment:
      PHP_IDE_CONFIG: "serverName=grades"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_DBNAME=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASS=${DB_PASSWORD}